services:
  - type: web
    name: sora-telegram-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: MAX_CONCURRENT_JOBS
        value: "1"
      - key: WORKER_POLL_INTERVAL
        value: "5000"
      - key: MAX_RETRY_ATTEMPTS
        value: "2"
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
